version: "3"

services:

  nginx:
    build:
      context: ./build/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
