version: "3"

services:

  foundryvtt-1:
    build:
      context: ./build/foundryvtt
      dockerfile: Dockerfile
    container_name: foundryvtt
    restart: unless-stopped
    ports:
      - 30000:30000 
    volumes:
      - ./data/default:/data
    networks:
      - backend

  nginx:
    build:
      context: ./build/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    
